version: "3"
services:
  api_gateway:
    build: ./api_gateway
    container_name: api_gateway
    ports:
      - 8080:8080
    networks:
      - node-network
  
  notify_service:
    build: ./notify_service
    container_name: notify_service
    networks:
      - node-network
  
  product_service:
    build: ./product_service
    container_name: product_service
    networks:
      - node-network

  shipping_service:
    build: ./shipping_service
    container_name: shipping_service
    networks:
      - node-network
  
networks:
  node-network:
    external: true